# Generated by Django 2.2.7 on 2019-12-05 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onetoone', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departments',
            name='emp_depart',
        ),
        migrations.RemoveField(
            model_name='roles',
            name='emp_name',
        ),
        migrations.AddField(
            model_name='employees',
            name='department_name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='onetoone.Departments'),
        ),
        migrations.AddField(
            model_name='employees',
            name='role_name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='onetoone.Roles'),
        ),
    ]
