# Generated by Django 2.2.6 on 2019-12-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onetoone', '0002_auto_20191206_0106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='department_name',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='role_name',
        ),
        migrations.AddField(
            model_name='employees',
            name='depart',
            field=models.ManyToManyField(to='onetoone.Departments'),
        ),
        migrations.RemoveField(
            model_name='employees',
            name='designation',
        ),
        migrations.AddField(
            model_name='employees',
            name='designation',
            field=models.ManyToManyField(to='onetoone.Roles'),
        ),
        migrations.AlterField(
            model_name='roles',
            name='descript',
            field=models.CharField(max_length=100),
        ),
    ]
