# Generated by Django 2.2.6 on 2019-12-22 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onetoone', '0003_auto_20191222_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='depart',
        ),
        migrations.AddField(
            model_name='employees',
            name='depart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='onetoone.Departments'),
        ),
        migrations.RemoveField(
            model_name='employees',
            name='designation',
        ),
        migrations.AddField(
            model_name='employees',
            name='designation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='onetoone.Roles'),
        ),
    ]
