# Generated by Django 2.2.6 on 2020-03-26 08:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('onetoone', '0005_auto_20200310_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='language',
            name='date_created',
        ),
        migrations.AddField(
            model_name='company',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language',
            name='updatedDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
