# Generated by Django 2.2.6 on 2019-12-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_auto_20191222_1738'),
        ('departments', '0002_auto_20191222_1738'),
        ('employees', '0002_auto_20191222_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department_name',
        ),
        migrations.AddField(
            model_name='employee',
            name='department_name',
            field=models.ManyToManyField(to='departments.Department'),
        ),
        migrations.RemoveField(
            model_name='employee',
            name='role_name',
        ),
        migrations.AddField(
            model_name='employee',
            name='role_name',
            field=models.ManyToManyField(to='roles.Role'),
        ),
    ]
