# Generated by Django 2.2.6 on 2019-12-22 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_auto_20191222_1738'),
        ('departments', '0002_auto_20191222_1738'),
        ('employees', '0004_auto_20191222_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department_name',
        ),
        migrations.AddField(
            model_name='employee',
            name='department_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.Department'),
        ),
        migrations.RemoveField(
            model_name='employee',
            name='role_name',
        ),
        migrations.AddField(
            model_name='employee',
            name='role_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='roles.Role'),
        ),
    ]
