# Generated by Django 2.2.6 on 2020-02-01 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serialpractice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskpract',
            name='dateCreated',
        ),
        migrations.RemoveField(
            model_name='taskpract',
            name='dateUpdated',
        ),
        migrations.RemoveField(
            model_name='taskpract',
            name='image',
        ),
        migrations.RemoveField(
            model_name='taskpract',
            name='user',
        ),
    ]
