# Generated by Django 2.2.6 on 2019-12-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='descriptt',
            field=models.CharField(max_length=100),
        ),
    ]
